version: '3.3'
services:
  redis-1:
    image: redis
    networks:
      - redis-cluster-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-1:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-2:
    image: redis
    networks:
      - redis-cluster-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-2:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-3:
    image: redis
    networks:
      - redis-cluster-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-3:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-4:
    image: redis
    networks:
      - redis-cluster-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-4:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-5:
    image: redis
    networks:
      - redis-cluster-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-5:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-6:
    image: redis
    networks:
      - redis-cluster-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data-6:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
  redis-data-4:
  redis-data-5:
  redis-data-6:

networks:
  redis-cluster-network: